// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDIHJoSnh-jT0ALaWHHSC1uDHGK3nvut0M',
    appId: '1:766252380168:web:8d098ec176dc52640561bd',
    messagingSenderId: '766252380168',
    projectId: 'firepass-78e13',
    authDomain: 'firepass-78e13.firebaseapp.com',
    storageBucket: 'firepass-78e13.appspot.com',
    measurementId: 'G-STZ35P1BHM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAB1fxudiFrgifBnrtDJIYjck1aMRHPw_8',
    appId: '1:766252380168:android:362d1920bc4047790561bd',
    messagingSenderId: '766252380168',
    projectId: 'firepass-78e13',
    storageBucket: 'firepass-78e13.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDIYgFCRV-m3VT5bvMu5afTzoUK9AB2irk',
    appId: '1:766252380168:ios:030ed49ba7b6049e0561bd',
    messagingSenderId: '766252380168',
    projectId: 'firepass-78e13',
    storageBucket: 'firepass-78e13.appspot.com',
    iosClientId: '766252380168-mgrg0kl7sei9d760h2p2dt8qhts87e5u.apps.googleusercontent.com',
    iosBundleId: 'com.example.firepass',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDIYgFCRV-m3VT5bvMu5afTzoUK9AB2irk',
    appId: '1:766252380168:ios:030ed49ba7b6049e0561bd',
    messagingSenderId: '766252380168',
    projectId: 'firepass-78e13',
    storageBucket: 'firepass-78e13.appspot.com',
    iosClientId: '766252380168-mgrg0kl7sei9d760h2p2dt8qhts87e5u.apps.googleusercontent.com',
    iosBundleId: 'com.example.firepass',
  );
}
